{
 "title": "Dashboard Pdfer",
 "description": "The number of clients to whom the server is responding.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Utilização de Recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Utilização da RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{name=\"pdfer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso da CPU do pdfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"pdfer\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Encriptação e Desencriptação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Tempo médio da encriptação",
   "type": "timeseries",
   "description": "contador que mede o tempo total, em segundos, gasto em operações de criptografia realizadas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(encryption_duration_seconds_sum[5m])/rate(encryption_duration_seconds_count[5m]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo Médio de Descriptação",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(decryption_duration_seconds_sum[5m])/rate(decryption_duration_seconds_count[5m]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ficheiros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ficheiros Criados pelo Servidor",
   "type": "stat",
   "description": "calcula o número de ficheiros criados ao longo de um determinado intervalo de tempo. Neste caso, está medindo o aumento total do contador files_created_total nos últimos 5 minutos.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "files_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ficheiros Lidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "files_read_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Atividade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Tentativas de Contacto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_clients{job=\"client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Numero Total de Conexões ao Servidor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(active_connections_total)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Pedidos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Latência Média das Requisições POST e GET",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(total_request_duration_seconds_sum[5m])) / sum(rate(total_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média dos Pedidos POST",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(post_request_latency_seconds_sum[5m])) / sum(rate(post_request_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência média dos pedidos GET",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(get_request_latency_seconds_sum[5m])) / sum(rate(get_request_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de pedidos http",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_http_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}