version: '3.7'

services:
  pdfer:
    image: golang:1.20
    container_name: pdfer
    working_dir: /app
    command: >
      sh -c "
      go get -d -v &&
      go build -v pdfer.go &&
      ./pdfer
      "
    ports:
      - "8081:8080"
    volumes:
      - ./pdfer.go:/app/pdfer.go
      - ./go.mod:/app/go.mod
      - nas_store:/app/store

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/etc/machine-id:/etc/machine-id:ro'
      - '/mnt/windows_docker/:/rootfs/var/lib/docker:ro'
    ports:
      - "8080:8080"
    devices:
      - /dev/kmsg:/dev/kmsg
    command:  
      - --docker_only=true
      - --disable_root_cgroup_stats=true
      - --disable_metrics=hugetlb
    privileged: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
  
  client: 
    image: python:3.9
    container_name: client
    volumes: 
      - ./client.py:/app/client.py
    working_dir: /app
    command: sh -c "pip install prometheus_client requests && python client.py" 
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

volumes:
  grafana-data:
  nas_store:
    external: true  # Indica que o volume é criado externamente