{
 "title": "Dashboard Pdfer 3",
 "description": "The number of clients to whom the server is responding.",
 "time": { "from": "2024-12-02T19:27:16.282Z", "to": "2024-12-02T20:07:16.282Z" },
 "panels": [
  {
   "title": "Número de Clientes Atual??",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_clients{job=\"client\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Conexões Ativas Encontradas Pdfer1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(active_connections_total{job=\"pdfer\", instance=\"192.168.1.11:8081\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões Ativas Encontradas Pdfer2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(active_connections_total{job=\"pdfer\", instance=\"192.168.1.13:8082\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilização de Recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Utilização da RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=\"/docker/1560ede39251cb4373a533c3f8b18ed51de39c2c4510daf58db14b4cb8d2eec6\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso da CPU do pdfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/docker/1560ede39251cb4373a533c3f8b18ed51de39c2c4510daf58db14b4cb8d2eec6\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Encriptação e Desencriptação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tempo Médio da Encriptação",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "encryption_duration_seconds_sum{job=\"pdfer\"} / encryption_duration_seconds_count{job=\"pdfer\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo Médio de Desencriptação",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "decryption_duration_seconds_sum{job=\"pdfer\"} / decryption_duration_seconds_count{job=\"pdfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ficheiros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Ficheiros Criados pelo Servidor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files_created_total{job=\"pdfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ficheiros Lidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files_read_total{job=\"pdfer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requisições", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Latência Média das Requisições POST e GET Pdfer2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_request_duration_seconds_sum{job=\"pdfer\", instance=\"192.168.1.13:8082\"}[5m])) / sum(rate(total_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média das Requisições POST e GET Pdfer2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_request_duration_seconds_sum{job=\"pdfer\", instance=\"192.168.1.13:8082\"}[5m])) / sum(rate(total_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média das Requisições POST e GET Pdfer1 e Pdfer2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "rate(total_request_duration_seconds_sum{job=\"pdfer\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tentativas de Pedidos HTTP por parte do Cliente??",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "post_request_success_total{job=\"client\"} + post_request_failure_total + get_request_success_total + get_request_failure_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de Requisições HTTP Bem Sucedidas??",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "post_request_success_total{job=\"client\"} + get_request_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pedidos Get e Post", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Get's Bem Sucedidos??",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "get_request_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput do Servidor",
   "type": "timeseries",
   "description": "Número de pedidos (GET E POST) que o servidor consegue processar por segundo.\nValor maior: Se o valor do throughput é alto, significa que o servidor está a processar mais requisições por segundo. Ou seja, o sistema está a conseguir lidar com uma grande quantidade de pedidos de GET e POST num curto período de tempo.\nValor menor: Se o valor do throughput é baixo, significa que o servidor está a processar menos requisições por segundo, o que pode indicar que há menos clientes ativos, o servidor está sobrecarregado, ou que existe um problema que está a diminuir a capacidade de resposta do servidor.\nAumento: Há mais pedidos a serem feitos pelos clientes e o servidor está a conseguir lidar bem com essa carga ou há melhorias de performance no servidor (talvez uma redução na latência ou tempos de processamento mais curtos), permitindo que ele processe mais pedidos por segundo.\nQueda: O número de clientes ou pedidos diminuiu ou o servidor está a ter dificuldade em processar os pedidos (por exemplo, devido a sobrecarga, latência elevada, ou gargalos de recursos como CPU e memória).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "rate(get_request_success_total[1m]) + rate(post_request_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post's Bem Sucedidos??",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "post_request_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GET's Falhados??",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_request_failure_total{instance=\"client:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post's Falhados",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "post_request_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Porcentagem de Erros HTTP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(post_request_failure_total[5m])) + sum(rate(get_request_failure_total[5m]))\n) / (\n  sum(rate(post_request_failure_total[5m])) + sum(rate(get_request_failure_total[5m])) +\n  sum(rate(post_request_success_total[5m])) + sum(rate(get_request_success_total[5m]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência média dos pedidos GET",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(get_request_latency_seconds_sum[5m])) / sum(rate(get_request_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média dos Pedidos POST",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(post_request_latency_seconds_sum[5m])) / sum(rate(post_request_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}