scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: 'client'
    scrape_interval: 5s
    static_configs:
      - targets: ['client:8000']

  - job_name: 'pdfer'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - '192.168.1.11:8081'  # Seu PDFER
        - '192.168.1.13:8082'  # PDFER da sua colega
       
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:80']
